```yml
language: node_js
node_js: "12"
branches:
  only:
    - master
    - main
cache:
  directories:
    - node_modules
services:
  - npm install -g codecov
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS testdb;'
  - codecov
script:
  - jest --ci --coverage && codecov
