```yml
language: node_js
node_js: "12"
branches:
  only:
    - master
    - main
cache:
  directories:
    - node_modules
services:
  - mysql
before_install:
  - npm install -g codecov
script:
  - jest --ci --coverage && codecov
  - codecov
  - bash <(curl -s https://codecov.io/bash)
env:
  - CODECOV_TOKEN="7089c610-e872-4726-865b-6e94654ed37a"