version: 2.1
orbs:
  node: circleci/node@3.0.0
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    steps:
      - codecov/upload:
          file: /coverage
workflows:
  node-tests:
    jobs:
      - node/test
