version: 2.1
orbs:
  node: circleci/node@3.0.0
  codecov: codecov/codecov@1.0.2
  doctl: digitalocean/cli@0.1.1
  k8s: circleci/kubernetes@0.1.0
jobs:
  build:
    docker:
      - image: "cimg/node:14.14.0"
        auth:
          username: mcereal
          password: eCE:3%.epa_@(Z&
    steps:
      - checkout

  test:
    executor:
      name: node/default
      tag: 14.14.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm test
          name: Run Jest test
workflows:
  node-tests:
    jobs:
      - test
