version: 2.1
orbs:
  node: circleci/node@3.0.0
  docker: circleci/docker@1.0.1
  doctl: digitalocean/cli@0.1.1
  k8s: circleci/kubernetes@0.1.0
jobs:
  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - attach_workspace:
          at: /home/circleci/project
      - digitalocean/install
      - digitalocean/initialize:
          digitalocean-access-token: ${DIGITAL_OCEAN_ACCESS_TOKEN}
      - run: doctl registry login
      - docker/build:
          image: "pomoduck"
          registry: "registry.digitalocaen.com"
          tag: "v0.1.0-dev"
      - docker/push:
          image: "pomoduck"
          registry: "registry.digitalocaen.com"
          tag: "v0.1.0-dev"

  test:
    executor:
      name: node/default
      tag: 14.14.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run ci:test
          name: Run Jest test
workflows:
  devops_flow:
    jobs:
      - test
      - build-and-push:
        image: "pomoduck/pomoduck:v0.1.0-dev"
          requires:
            - test
      #Envs: AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_REGION, AWS_ECR_ACCOUNT_URL
      # - aws-ecr/build-and-push-image:
      #     repo: pomoduck
      #     tag: "latest,v0.1.${CIRCLE_BUILD_NUM}"
      #     dockerfile: build/Dockerfile.prod
      #     path: .
      #     requires:
      #       - test
