version: 2.1
orbs:
  node: circleci/node@3.0.0
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    docker:
      - image: "cimg/node:14.14.0"
        auth:
          username: mcereal
          password: eCE:3%.epa_@(Z&
    steps:
      - run: node --version
      - run: jest --ci --coverage && codecov -t 7089c610-e872-4726-865b-6e94654ed37a
      - codecov/upload:
          file: "./coverage/clover.xml"
workflows:
  node-tests:
    jobs:
      - node/test
