kind: Deployment
apiVersion: apps/v1
metadata:
  name: pomoduck
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pomoduck
  template:
    metadata:
      labels:
        app: pomoduck
    spec:
      containers:
        - name: pomoduck
          image: registry.digitalocean.com/pomoduck/pomoduck:v0.1.0-prod
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
          env:
            - name: EXPRESS_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: express-configmap
                  key: EXPRESS_SERVICE
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: pomoduck
spec:
  selector:
    app: pomoduck
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
