apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pomoduck-ingress
  labels:
    name: pomoduck-ingress
spec:
  rules:
    - host: pomoduck.com
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                serviceName: pomoduck-frontend.default.svc.cluster.local
                servicePort: 80
